Repository Sejong-Java-Study/gonghak98, pull requests merged in 2024-08, with the labels that each got.

#44 Sj 110 홈페이지 로고파일 수정
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/navbar.html
Labels: :wrench: 기능 추가, 디자인

#49 refactor: CompletedCoursesService
  src/main/java/com/example/gimmegonghakauth/service/CompletedCoursesService.java
Labels: :hammer: 리팩토링, 서비스

#50 refactor: init file data
  src/main/java/com/example/gimmegonghakauth/InitFileData.java
  src/main/java/com/example/gimmegonghakauth/service/recommend/MajorName.java
Labels: :hammer: 리팩토링, 서비스

#51 fix: calculate
  src/main/java/com/example/gimmegonghakauth/InitData.java
  src/main/java/com/example/gimmegonghakauth/constant/CourseCategoryConst.java
  src/main/java/com/example/gimmegonghakauth/dao/GonghakCorusesDao.java
  src/main/java/com/example/gimmegonghakauth/dao/GonghakDao.java
  src/main/java/com/example/gimmegonghakauth/domain/CompletedCoursesDomain.java
  src/main/java/com/example/gimmegonghakauth/service/CompletedCoursesService.java
  src/main/java/com/example/gimmegonghakauth/service/GonghakCalculateService.java
  src/main/java/com/example/gimmegonghakauth/service/recommend/ComputerMajorGonghakRecommendService.java
  src/main/java/com/example/gimmegonghakauth/service/recommend/ElecInfoMajorGonghakRecommendService.java
  src/test/java/com/example/gimmegonghakauth/Service/CompletedCoursesServiceDataTest.java
  src/test/java/com/example/gimmegonghakauth/dao/GonghakRepositoryTest.java
Labels: :bug: 버그, :hammer: 리팩토링, 서비스

#46 refactor: GonghakDao 빈 등록 중복 제거
  src/main/java/com/example/gimmegonghakauth/config/GonghakConfig.java
Labels: :hammer: 리팩토링, 서비스

#45 feat: 이슈/PR 템플릿 추가
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :scroll: 문서 작업

#52 Develop to Main
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/example/gimmegonghakauth/InitData.java
  src/main/java/com/example/gimmegonghakauth/InitFileData.java
  src/main/java/com/example/gimmegonghakauth/config/GonghakConfig.java
  src/main/java/com/example/gimmegonghakauth/constant/AbeekTypeConst.java
  src/main/java/com/example/gimmegonghakauth/constant/CourseCategoryConst.java
  src/main/java/com/example/gimmegonghakauth/controller/StatusController.java
  src/main/java/com/example/gimmegonghakauth/dao/GonghakCorusesDao.java
  src/main/java/com/example/gimmegonghakauth/dao/GonghakDao.java
  src/main/java/com/example/gimmegonghakauth/domain/CompletedCoursesDomain.java
  src/main/java/com/example/gimmegonghakauth/service/CompletedCoursesService.java
  src/main/java/com/example/gimmegonghakauth/service/GonghakCalculateService.java
  src/main/java/com/example/gimmegonghakauth/service/recommend/ComputerMajorGonghakRecommendService.java
  src/main/java/com/example/gimmegonghakauth/service/recommend/ElecInfoMajorGonghakRecommendService.java
  src/main/java/com/example/gimmegonghakauth/service/recommend/MajorName.java
  src/main/java/com/example/gimmegonghakauth/service/recommend/RecommendServiceSelectManager.java
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/navbar.html
  src/test/java/com/example/gimmegonghakauth/Service/CompletedCoursesServiceDataTest.java
  src/test/java/com/example/gimmegonghakauth/dao/GonghakRepositoryTest.java
Labels: :wrench: 기능 추가, 디자인, 서비스

#59 refactor: GonghakRepository 리팩토링
  src/main/java/com/example/gimmegonghakauth/InitData.java
  src/main/java/com/example/gimmegonghakauth/InitFileData.java
  src/main/java/com/example/gimmegonghakauth/dao/GonghakCoursesDao.java
  src/main/java/com/example/gimmegonghakauth/dao/GonghakDao.java
  src/main/java/com/example/gimmegonghakauth/dao/GonghakRepository.java
  src/main/java/com/example/gimmegonghakauth/service/GonghakCalculateService.java
  src/main/java/com/example/gimmegonghakauth/service/recommend/ComputerMajorGonghakRecommendService.java
  src/main/java/com/example/gimmegonghakauth/service/recommend/ElecInfoMajorGonghakRecommendService.java
  src/test/java/com/example/gimmegonghakauth/Service/GonghakCalculateServiceTest.java
  src/test/java/com/example/gimmegonghakauth/dao/GonghakRepositoryTest.java
  src/test/java/com/example/gimmegonghakauth/domain/DomainTest.java
Labels: :hammer: 리팩토링, 서비스

#64 feat: 피드백하기 버튼 추가
  src/main/resources/templates/layout/navbar.html
Labels: :wrench: 기능 추가, 디자인
